/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select46 string

// List of $select46
const (
	ID_Select46 Select46 = "id"
	NUMBER_Select46 Select46 = "number"
	DISPLAY_NAME_Select46 Select46 = "displayName"
	CATEGORY_Select46 Select46 = "category"
	SUB_CATEGORY_Select46 Select46 = "subCategory"
	BLOCKED_Select46 Select46 = "blocked"
	LAST_MODIFIED_DATE_TIME_Select46 Select46 = "lastModifiedDateTime"
)
