/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand32 string

// List of $expand32
const (
	PICTURE_Expand32 Expand32 = "picture"
	DEFAULT_DIMENSIONS_Expand32 Expand32 = "defaultDimensions"
	TIME_REGISTRATION_ENTRIES_Expand32 Expand32 = "timeRegistrationEntries"
)
