/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select28 string

// List of $select28
const (
	ID_Select28 Select28 = "id"
	DISPLAY_NAME_Select28 Select28 = "displayName"
	ADDRESS_Select28 Select28 = "address"
	PHONE_NUMBER_Select28 Select28 = "phoneNumber"
	FAX_NUMBER_Select28 Select28 = "faxNumber"
	EMAIL_Select28 Select28 = "email"
	WEBSITE_Select28 Select28 = "website"
	TAX_REGISTRATION_NUMBER_Select28 Select28 = "taxRegistrationNumber"
	CURRENCY_CODE_Select28 Select28 = "currencyCode"
	CURRENT_FISCAL_YEAR_START_DATE_Select28 Select28 = "currentFiscalYearStartDate"
	INDUSTRY_Select28 Select28 = "industry"
	PICTURE_Select28 Select28 = "picture"
	LAST_MODIFIED_DATE_TIME_Select28 Select28 = "lastModifiedDateTime"
)
