/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select86 string

// List of $select86
const (
	ID_Select86 Select86 = "id"
	CODE_Select86 Select86 = "code"
	DISPLAY_NAME_Select86 Select86 = "displayName"
	DUE_DATE_CALCULATION_Select86 Select86 = "dueDateCalculation"
	DISCOUNT_DATE_CALCULATION_Select86 Select86 = "discountDateCalculation"
	DISCOUNT_PERCENT_Select86 Select86 = "discountPercent"
	CALCULATE_DISCOUNT_ON_CREDIT_MEMOS_Select86 Select86 = "calculateDiscountOnCreditMemos"
	LAST_MODIFIED_DATE_TIME_Select86 Select86 = "lastModifiedDateTime"
)
