/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select84 string

// List of $select84
const (
	PARENT_ID_Select84 Select84 = "parentId"
	ID_Select84 Select84 = "id"
	CODE_Select84 Select84 = "code"
	DISPLAY_NAME_Select84 Select84 = "displayName"
	VALUE_ID_Select84 Select84 = "valueId"
	VALUE_CODE_Select84 Select84 = "valueCode"
	VALUE_DISPLAY_NAME_Select84 Select84 = "valueDisplayName"
)
