/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand14 string

// List of $expand14
const (
	SALES_INVOICE_LINES_Expand14 Expand14 = "salesInvoiceLines"
	PDF_DOCUMENT_Expand14 Expand14 = "pdfDocument"
	CUSTOMER_Expand14 Expand14 = "customer"
	CURRENCY_Expand14 Expand14 = "currency"
	PAYMENT_TERM_Expand14 Expand14 = "paymentTerm"
	SHIPMENT_METHOD_Expand14 Expand14 = "shipmentMethod"
)
