/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select110 string

// List of $select110
const (
	LINE_NUMBER_Select110 Select110 = "lineNumber"
	DISPLAY_Select110 Select110 = "display"
	BALANCE_Select110 Select110 = "balance"
	LINE_TYPE_Select110 Select110 = "lineType"
	INDENTATION_Select110 Select110 = "indentation"
	DATE_FILTER_Select110 Select110 = "dateFilter"
)
