/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select30 string

// List of $select30
const (
	ID_Select30 Select30 = "id"
	NUMBER_Select30 Select30 = "number"
	EXTERNAL_DOCUMENT_NUMBER_Select30 Select30 = "externalDocumentNumber"
	INVOICE_DATE_Select30 Select30 = "invoiceDate"
	DUE_DATE_Select30 Select30 = "dueDate"
	CUSTOMER_PURCHASE_ORDER_REFERENCE_Select30 Select30 = "customerPurchaseOrderReference"
	CUSTOMER_ID_Select30 Select30 = "customerId"
	CONTACT_ID_Select30 Select30 = "contactId"
	CUSTOMER_NUMBER_Select30 Select30 = "customerNumber"
	CUSTOMER_NAME_Select30 Select30 = "customerName"
	BILL_TO_NAME_Select30 Select30 = "billToName"
	BILL_TO_CUSTOMER_ID_Select30 Select30 = "billToCustomerId"
	BILL_TO_CUSTOMER_NUMBER_Select30 Select30 = "billToCustomerNumber"
	SHIP_TO_NAME_Select30 Select30 = "shipToName"
	SHIP_TO_CONTACT_Select30 Select30 = "shipToContact"
	SELLING_POSTAL_ADDRESS_Select30 Select30 = "sellingPostalAddress"
	BILLING_POSTAL_ADDRESS_Select30 Select30 = "billingPostalAddress"
	SHIPPING_POSTAL_ADDRESS_Select30 Select30 = "shippingPostalAddress"
	CURRENCY_ID_Select30 Select30 = "currencyId"
	CURRENCY_CODE_Select30 Select30 = "currencyCode"
	ORDER_ID_Select30 Select30 = "orderId"
	ORDER_NUMBER_Select30 Select30 = "orderNumber"
	PAYMENT_TERMS_ID_Select30 Select30 = "paymentTermsId"
	SHIPMENT_METHOD_ID_Select30 Select30 = "shipmentMethodId"
	SALESPERSON_Select30 Select30 = "salesperson"
	PRICES_INCLUDE_TAX_Select30 Select30 = "pricesIncludeTax"
	REMAINING_AMOUNT_Select30 Select30 = "remainingAmount"
	DISCOUNT_AMOUNT_Select30 Select30 = "discountAmount"
	DISCOUNT_APPLIED_BEFORE_TAX_Select30 Select30 = "discountAppliedBeforeTax"
	TOTAL_AMOUNT_EXCLUDING_TAX_Select30 Select30 = "totalAmountExcludingTax"
	TOTAL_TAX_AMOUNT_Select30 Select30 = "totalTaxAmount"
	TOTAL_AMOUNT_INCLUDING_TAX_Select30 Select30 = "totalAmountIncludingTax"
	STATUS_Select30 Select30 = "status"
	LAST_MODIFIED_DATE_TIME_Select30 Select30 = "lastModifiedDateTime"
	PHONE_NUMBER_Select30 Select30 = "phoneNumber"
	EMAIL_Select30 Select30 = "email"
)
