/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select106 string

// List of $select106
const (
	CUSTOMER_ID_Select106 Select106 = "customerId"
	CUSTOMER_NUMBER_Select106 Select106 = "customerNumber"
	NAME_Select106 Select106 = "name"
	CURRENCY_CODE_Select106 Select106 = "currencyCode"
	BALANCE_DUE_Select106 Select106 = "balanceDue"
	CURRENT_AMOUNT_Select106 Select106 = "currentAmount"
	PERIOD1_AMOUNT_Select106 Select106 = "period1Amount"
	PERIOD2_AMOUNT_Select106 Select106 = "period2Amount"
	PERIOD3_AMOUNT_Select106 Select106 = "period3Amount"
	AGED_AS_OF_DATE_Select106 Select106 = "agedAsOfDate"
	PERIOD_LENGTH_FILTER_Select106 Select106 = "periodLengthFilter"
)
