/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select72 string

// List of $select72
const (
	ID_Select72 Select72 = "id"
	POSTING_DATE_Select72 Select72 = "postingDate"
	DOCUMENT_NUMBER_Select72 Select72 = "documentNumber"
	DOCUMENT_TYPE_Select72 Select72 = "documentType"
	ACCOUNT_ID_Select72 Select72 = "accountId"
	ACCOUNT_NUMBER_Select72 Select72 = "accountNumber"
	DESCRIPTION_Select72 Select72 = "description"
	DEBIT_AMOUNT_Select72 Select72 = "debitAmount"
	CREDIT_AMOUNT_Select72 Select72 = "creditAmount"
	DIMENSIONS_Select72 Select72 = "dimensions"
	LAST_MODIFIED_DATE_TIME_Select72 Select72 = "lastModifiedDateTime"
)
