/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type ModelSelect string

// List of $select
const (
	ID_ModelSelect ModelSelect = "id"
	SYSTEM_VERSION_ModelSelect ModelSelect = "systemVersion"
	NAME_ModelSelect ModelSelect = "name"
	DISPLAY_NAME_ModelSelect ModelSelect = "displayName"
	BUSINESS_PROFILE_ID_ModelSelect ModelSelect = "businessProfileId"
)
