/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select144 string

// List of $select144
const (
	ID_Select144 Select144 = "id"
	NUMBER_Select144 Select144 = "number"
	DISPLAY_NAME_Select144 Select144 = "displayName"
)
