/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select34 string

// List of $select34
const (
	ID_Select34 Select34 = "id"
	CONTENT_Select34 Select34 = "content"
)
