/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select118 string

// List of $select118
const (
	ID_Select118 Select118 = "id"
	NUMBER_Select118 Select118 = "number"
	EXTERNAL_DOCUMENT_NUMBER_Select118 Select118 = "externalDocumentNumber"
	DOCUMENT_DATE_Select118 Select118 = "documentDate"
	DUE_DATE_Select118 Select118 = "dueDate"
	CUSTOMER_ID_Select118 Select118 = "customerId"
	CONTACT_ID_Select118 Select118 = "contactId"
	CUSTOMER_NUMBER_Select118 Select118 = "customerNumber"
	CUSTOMER_NAME_Select118 Select118 = "customerName"
	BILL_TO_NAME_Select118 Select118 = "billToName"
	BILL_TO_CUSTOMER_ID_Select118 Select118 = "billToCustomerId"
	BILL_TO_CUSTOMER_NUMBER_Select118 Select118 = "billToCustomerNumber"
	SHIP_TO_NAME_Select118 Select118 = "shipToName"
	SHIP_TO_CONTACT_Select118 Select118 = "shipToContact"
	SELLING_POSTAL_ADDRESS_Select118 Select118 = "sellingPostalAddress"
	BILLING_POSTAL_ADDRESS_Select118 Select118 = "billingPostalAddress"
	SHIPPING_POSTAL_ADDRESS_Select118 Select118 = "shippingPostalAddress"
	CURRENCY_ID_Select118 Select118 = "currencyId"
	CURRENCY_CODE_Select118 Select118 = "currencyCode"
	PAYMENT_TERMS_ID_Select118 Select118 = "paymentTermsId"
	SHIPMENT_METHOD_ID_Select118 Select118 = "shipmentMethodId"
	SALESPERSON_Select118 Select118 = "salesperson"
	DISCOUNT_AMOUNT_Select118 Select118 = "discountAmount"
	TOTAL_AMOUNT_EXCLUDING_TAX_Select118 Select118 = "totalAmountExcludingTax"
	TOTAL_TAX_AMOUNT_Select118 Select118 = "totalTaxAmount"
	TOTAL_AMOUNT_INCLUDING_TAX_Select118 Select118 = "totalAmountIncludingTax"
	STATUS_Select118 Select118 = "status"
	SENT_DATE_Select118 Select118 = "sentDate"
	VALID_UNTIL_DATE_Select118 Select118 = "validUntilDate"
	ACCEPTED_DATE_Select118 Select118 = "acceptedDate"
	LAST_MODIFIED_DATE_TIME_Select118 Select118 = "lastModifiedDateTime"
	PHONE_NUMBER_Select118 Select118 = "phoneNumber"
	EMAIL_Select118 Select118 = "email"
)
