/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand42 string

// List of $expand42
const (
	DIMENSION_VALUES_Expand42 Expand42 = "dimensionValues"
)
