/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select120 string

// List of $select120
const (
	ID_Select120 Select120 = "id"
	DOCUMENT_ID_Select120 Select120 = "documentId"
	SEQUENCE_Select120 Select120 = "sequence"
	ITEM_ID_Select120 Select120 = "itemId"
	ACCOUNT_ID_Select120 Select120 = "accountId"
	LINE_TYPE_Select120 Select120 = "lineType"
	LINE_DETAILS_Select120 Select120 = "lineDetails"
	DESCRIPTION_Select120 Select120 = "description"
	UNIT_OF_MEASURE_ID_Select120 Select120 = "unitOfMeasureId"
	UNIT_OF_MEASURE_Select120 Select120 = "unitOfMeasure"
	UNIT_PRICE_Select120 Select120 = "unitPrice"
	QUANTITY_Select120 Select120 = "quantity"
	DISCOUNT_AMOUNT_Select120 Select120 = "discountAmount"
	DISCOUNT_PERCENT_Select120 Select120 = "discountPercent"
	DISCOUNT_APPLIED_BEFORE_TAX_Select120 Select120 = "discountAppliedBeforeTax"
	AMOUNT_EXCLUDING_TAX_Select120 Select120 = "amountExcludingTax"
	TAX_CODE_Select120 Select120 = "taxCode"
	TAX_PERCENT_Select120 Select120 = "taxPercent"
	TOTAL_TAX_AMOUNT_Select120 Select120 = "totalTaxAmount"
	AMOUNT_INCLUDING_TAX_Select120 Select120 = "amountIncludingTax"
	NET_AMOUNT_Select120 Select120 = "netAmount"
	NET_TAX_AMOUNT_Select120 Select120 = "netTaxAmount"
	NET_AMOUNT_INCLUDING_TAX_Select120 Select120 = "netAmountIncludingTax"
)
