/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select14 string

// List of $select14
const (
	ID_Select14 Select14 = "id"
	NUMBER_Select14 Select14 = "number"
	BALANCE_Select14 Select14 = "balance"
	TOTAL_SALES_EXCLUDING_TAX_Select14 Select14 = "totalSalesExcludingTax"
	OVERDUE_AMOUNT_Select14 Select14 = "overdueAmount"
)
