/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select104 string

// List of $select104
const (
	ID_Select104 Select104 = "id"
	CODE_Select104 Select104 = "code"
	DISPLAY_NAME_Select104 Select104 = "displayName"
	INTERNATIONAL_STANDARD_CODE_Select104 Select104 = "internationalStandardCode"
	LAST_MODIFIED_DATE_TIME_Select104 Select104 = "lastModifiedDateTime"
)
