/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select32 string

// List of $select32
const (
	ID_Select32 Select32 = "id"
	DOCUMENT_ID_Select32 Select32 = "documentId"
	SEQUENCE_Select32 Select32 = "sequence"
	ITEM_ID_Select32 Select32 = "itemId"
	ACCOUNT_ID_Select32 Select32 = "accountId"
	LINE_TYPE_Select32 Select32 = "lineType"
	LINE_DETAILS_Select32 Select32 = "lineDetails"
	DESCRIPTION_Select32 Select32 = "description"
	UNIT_OF_MEASURE_ID_Select32 Select32 = "unitOfMeasureId"
	UNIT_OF_MEASURE_Select32 Select32 = "unitOfMeasure"
	UNIT_PRICE_Select32 Select32 = "unitPrice"
	QUANTITY_Select32 Select32 = "quantity"
	DISCOUNT_AMOUNT_Select32 Select32 = "discountAmount"
	DISCOUNT_PERCENT_Select32 Select32 = "discountPercent"
	DISCOUNT_APPLIED_BEFORE_TAX_Select32 Select32 = "discountAppliedBeforeTax"
	AMOUNT_EXCLUDING_TAX_Select32 Select32 = "amountExcludingTax"
	TAX_CODE_Select32 Select32 = "taxCode"
	TAX_PERCENT_Select32 Select32 = "taxPercent"
	TOTAL_TAX_AMOUNT_Select32 Select32 = "totalTaxAmount"
	AMOUNT_INCLUDING_TAX_Select32 Select32 = "amountIncludingTax"
	INVOICE_DISCOUNT_ALLOCATION_Select32 Select32 = "invoiceDiscountAllocation"
	NET_AMOUNT_Select32 Select32 = "netAmount"
	NET_TAX_AMOUNT_Select32 Select32 = "netTaxAmount"
	NET_AMOUNT_INCLUDING_TAX_Select32 Select32 = "netAmountIncludingTax"
	SHIPMENT_DATE_Select32 Select32 = "shipmentDate"
)
