/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select48 string

// List of $select48
const (
	ID_Select48 Select48 = "id"
	CODE_Select48 Select48 = "code"
	DISPLAY_NAME_Select48 Select48 = "displayName"
	TAX_TYPE_Select48 Select48 = "taxType"
	LAST_MODIFIED_DATE_TIME_Select48 Select48 = "lastModifiedDateTime"
)
