/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select12 string

// List of $select12
const (
	ID_Select12 Select12 = "id"
	NUMBER_Select12 Select12 = "number"
	DISPLAY_NAME_Select12 Select12 = "displayName"
	TYPE__Select12 Select12 = "type"
	ADDRESS_Select12 Select12 = "address"
	PHONE_NUMBER_Select12 Select12 = "phoneNumber"
	EMAIL_Select12 Select12 = "email"
	WEBSITE_Select12 Select12 = "website"
	TAX_LIABLE_Select12 Select12 = "taxLiable"
	TAX_AREA_ID_Select12 Select12 = "taxAreaId"
	TAX_AREA_DISPLAY_NAME_Select12 Select12 = "taxAreaDisplayName"
	TAX_REGISTRATION_NUMBER_Select12 Select12 = "taxRegistrationNumber"
	CURRENCY_ID_Select12 Select12 = "currencyId"
	CURRENCY_CODE_Select12 Select12 = "currencyCode"
	PAYMENT_TERMS_ID_Select12 Select12 = "paymentTermsId"
	SHIPMENT_METHOD_ID_Select12 Select12 = "shipmentMethodId"
	PAYMENT_METHOD_ID_Select12 Select12 = "paymentMethodId"
	BLOCKED_Select12 Select12 = "blocked"
	LAST_MODIFIED_DATE_TIME_Select12 Select12 = "lastModifiedDateTime"
)
