/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select68 string

// List of $select68
const (
	ID_Select68 Select68 = "id"
	EMPLOYEE_ID_Select68 Select68 = "employeeId"
	EMPLOYEE_NUMBER_Select68 Select68 = "employeeNumber"
	JOB_ID_Select68 Select68 = "jobId"
	JOB_NUMBER_Select68 Select68 = "jobNumber"
	ABSENCE_Select68 Select68 = "absence"
	LINE_NUMBER_Select68 Select68 = "lineNumber"
	DATE_Select68 Select68 = "date"
	QUANTITY_Select68 Select68 = "quantity"
	STATUS_Select68 Select68 = "status"
	UNIT_OF_MEASURE_ID_Select68 Select68 = "unitOfMeasureId"
	UNIT_OF_MEASURE_Select68 Select68 = "unitOfMeasure"
	DIMENSIONS_Select68 Select68 = "dimensions"
	LAST_MODFIED_DATE_TIME_Select68 Select68 = "lastModfiedDateTime"
)
