/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select4 string

// List of $select4
const (
	ID_Select4 Select4 = "id"
	WIDTH_Select4 Select4 = "width"
	HEIGHT_Select4 Select4 = "height"
	CONTENT_TYPE_Select4 Select4 = "contentType"
	CONTENT_Select4 Select4 = "content"
)
