/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select92 string

// List of $select92
const (
	LINE_NUMBER_Select92 Select92 = "lineNumber"
	DISPLAY_Select92 Select92 = "display"
	NET_CHANGE_Select92 Select92 = "netChange"
	LINE_TYPE_Select92 Select92 = "lineType"
	INDENTATION_Select92 Select92 = "indentation"
	DATE_FILTER_Select92 Select92 = "dateFilter"
)
