/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select62 string

// List of $select62
const (
	ID_Select62 Select62 = "id"
	NUMBER_Select62 Select62 = "number"
	DISPLAY_NAME_Select62 Select62 = "displayName"
	GIVEN_NAME_Select62 Select62 = "givenName"
	MIDDLE_NAME_Select62 Select62 = "middleName"
	SURNAME_Select62 Select62 = "surname"
	JOB_TITLE_Select62 Select62 = "jobTitle"
	ADDRESS_Select62 Select62 = "address"
	PHONE_NUMBER_Select62 Select62 = "phoneNumber"
	MOBILE_PHONE_Select62 Select62 = "mobilePhone"
	EMAIL_Select62 Select62 = "email"
	PERSONAL_EMAIL_Select62 Select62 = "personalEmail"
	EMPLOYMENT_DATE_Select62 Select62 = "employmentDate"
	TERMINATION_DATE_Select62 Select62 = "terminationDate"
	STATUS_Select62 Select62 = "status"
	BIRTH_DATE_Select62 Select62 = "birthDate"
	STATISTICS_GROUP_CODE_Select62 Select62 = "statisticsGroupCode"
	LAST_MODIFIED_DATE_TIME_Select62 Select62 = "lastModifiedDateTime"
)
