/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand60 string

// List of $expand60
const (
	SALES_CREDIT_MEMO_LINES_Expand60 Expand60 = "salesCreditMemoLines"
	PDF_DOCUMENT_Expand60 Expand60 = "pdfDocument"
	CUSTOMER_Expand60 Expand60 = "customer"
	CURRENCY_Expand60 Expand60 = "currency"
	PAYMENT_TERM_Expand60 Expand60 = "paymentTerm"
	SHIPMENT_METHOD_Expand60 Expand60 = "shipmentMethod"
)
