/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select98 string

// List of $select98
const (
	ID_Select98 Select98 = "id"
	DOCUMENT_ID_Select98 Select98 = "documentId"
	SEQUENCE_Select98 Select98 = "sequence"
	ITEM_ID_Select98 Select98 = "itemId"
	ACCOUNT_ID_Select98 Select98 = "accountId"
	LINE_TYPE_Select98 Select98 = "lineType"
	LINE_DETAILS_Select98 Select98 = "lineDetails"
	DESCRIPTION_Select98 Select98 = "description"
	UNIT_OF_MEASURE_ID_Select98 Select98 = "unitOfMeasureId"
	UNIT_OF_MEASURE_Select98 Select98 = "unitOfMeasure"
	QUANTITY_Select98 Select98 = "quantity"
	UNIT_PRICE_Select98 Select98 = "unitPrice"
	DISCOUNT_AMOUNT_Select98 Select98 = "discountAmount"
	DISCOUNT_PERCENT_Select98 Select98 = "discountPercent"
	DISCOUNT_APPLIED_BEFORE_TAX_Select98 Select98 = "discountAppliedBeforeTax"
	AMOUNT_EXCLUDING_TAX_Select98 Select98 = "amountExcludingTax"
	TAX_CODE_Select98 Select98 = "taxCode"
	TAX_PERCENT_Select98 Select98 = "taxPercent"
	TOTAL_TAX_AMOUNT_Select98 Select98 = "totalTaxAmount"
	AMOUNT_INCLUDING_TAX_Select98 Select98 = "amountIncludingTax"
	INVOICE_DISCOUNT_ALLOCATION_Select98 Select98 = "invoiceDiscountAllocation"
	NET_AMOUNT_Select98 Select98 = "netAmount"
	NET_TAX_AMOUNT_Select98 Select98 = "netTaxAmount"
	NET_AMOUNT_INCLUDING_TAX_Select98 Select98 = "netAmountIncludingTax"
	SHIPMENT_DATE_Select98 Select98 = "shipmentDate"
	SHIPPED_QUANTITY_Select98 Select98 = "shippedQuantity"
	INVOICED_QUANTITY_Select98 Select98 = "invoicedQuantity"
	INVOICE_QUANTITY_Select98 Select98 = "invoiceQuantity"
	SHIP_QUANTITY_Select98 Select98 = "shipQuantity"
)
