/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand46 string

// List of $expand46
const (
	SALES_ORDER_LINES_Expand46 Expand46 = "salesOrderLines"
	CUSTOMER_Expand46 Expand46 = "customer"
	CURRENCY_Expand46 Expand46 = "currency"
	PAYMENT_TERM_Expand46 Expand46 = "paymentTerm"
	SHIPMENT_METHOD_Expand46 Expand46 = "shipmentMethod"
)
