/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select52 string

// List of $select52
const (
	ID_Select52 Select52 = "id"
	JOURNAL_DISPLAY_NAME_Select52 Select52 = "journalDisplayName"
	LINE_NUMBER_Select52 Select52 = "lineNumber"
	ACCOUNT_TYPE_Select52 Select52 = "accountType"
	ACCOUNT_ID_Select52 Select52 = "accountId"
	ACCOUNT_NUMBER_Select52 Select52 = "accountNumber"
	POSTING_DATE_Select52 Select52 = "postingDate"
	DOCUMENT_NUMBER_Select52 Select52 = "documentNumber"
	EXTERNAL_DOCUMENT_NUMBER_Select52 Select52 = "externalDocumentNumber"
	AMOUNT_Select52 Select52 = "amount"
	DESCRIPTION_Select52 Select52 = "description"
	COMMENT_Select52 Select52 = "comment"
	DIMENSIONS_Select52 Select52 = "dimensions"
	LAST_MODIFIED_DATE_TIME_Select52 Select52 = "lastModifiedDateTime"
)
