/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select96 string

// List of $select96
const (
	ID_Select96 Select96 = "id"
	NUMBER_Select96 Select96 = "number"
	EXTERNAL_DOCUMENT_NUMBER_Select96 Select96 = "externalDocumentNumber"
	ORDER_DATE_Select96 Select96 = "orderDate"
	CUSTOMER_ID_Select96 Select96 = "customerId"
	CONTACT_ID_Select96 Select96 = "contactId"
	CUSTOMER_NUMBER_Select96 Select96 = "customerNumber"
	CUSTOMER_NAME_Select96 Select96 = "customerName"
	BILL_TO_NAME_Select96 Select96 = "billToName"
	BILL_TO_CUSTOMER_ID_Select96 Select96 = "billToCustomerId"
	BILL_TO_CUSTOMER_NUMBER_Select96 Select96 = "billToCustomerNumber"
	SHIP_TO_NAME_Select96 Select96 = "shipToName"
	SHIP_TO_CONTACT_Select96 Select96 = "shipToContact"
	SELLING_POSTAL_ADDRESS_Select96 Select96 = "sellingPostalAddress"
	BILLING_POSTAL_ADDRESS_Select96 Select96 = "billingPostalAddress"
	SHIPPING_POSTAL_ADDRESS_Select96 Select96 = "shippingPostalAddress"
	CURRENCY_ID_Select96 Select96 = "currencyId"
	CURRENCY_CODE_Select96 Select96 = "currencyCode"
	PRICES_INCLUDE_TAX_Select96 Select96 = "pricesIncludeTax"
	PAYMENT_TERMS_ID_Select96 Select96 = "paymentTermsId"
	SHIPMENT_METHOD_ID_Select96 Select96 = "shipmentMethodId"
	SALESPERSON_Select96 Select96 = "salesperson"
	PARTIAL_SHIPPING_Select96 Select96 = "partialShipping"
	REQUESTED_DELIVERY_DATE_Select96 Select96 = "requestedDeliveryDate"
	DISCOUNT_AMOUNT_Select96 Select96 = "discountAmount"
	DISCOUNT_APPLIED_BEFORE_TAX_Select96 Select96 = "discountAppliedBeforeTax"
	TOTAL_AMOUNT_EXCLUDING_TAX_Select96 Select96 = "totalAmountExcludingTax"
	TOTAL_TAX_AMOUNT_Select96 Select96 = "totalTaxAmount"
	TOTAL_AMOUNT_INCLUDING_TAX_Select96 Select96 = "totalAmountIncludingTax"
	FULLY_SHIPPED_Select96 Select96 = "fullyShipped"
	STATUS_Select96 Select96 = "status"
	LAST_MODIFIED_DATE_TIME_Select96 Select96 = "lastModifiedDateTime"
	PHONE_NUMBER_Select96 Select96 = "phoneNumber"
	EMAIL_Select96 Select96 = "email"
)
