/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select40 string

// List of $select40
const (
	ID_Select40 Select40 = "id"
	CODE_Select40 Select40 = "code"
	DISPLAY_NAME_Select40 Select40 = "displayName"
	LAST_MODIFIED_DATE_TIME_Select40 Select40 = "lastModifiedDateTime"
	BALANCING_ACCOUNT_ID_Select40 Select40 = "balancingAccountId"
	BALANCING_ACCOUNT_NUMBER_Select40 Select40 = "balancingAccountNumber"
)
