/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select138 string

// List of $select138
const (
	ID_Select138 Select138 = "id"
	DOCUMENT_ID_Select138 Select138 = "documentId"
	SEQUENCE_Select138 Select138 = "sequence"
	ITEM_ID_Select138 Select138 = "itemId"
	ACCOUNT_ID_Select138 Select138 = "accountId"
	LINE_TYPE_Select138 Select138 = "lineType"
	LINE_DETAILS_Select138 Select138 = "lineDetails"
	DESCRIPTION_Select138 Select138 = "description"
	UNIT_OF_MEASURE_Select138 Select138 = "unitOfMeasure"
	UNIT_COST_Select138 Select138 = "unitCost"
	QUANTITY_Select138 Select138 = "quantity"
	DISCOUNT_AMOUNT_Select138 Select138 = "discountAmount"
	DISCOUNT_PERCENT_Select138 Select138 = "discountPercent"
	DISCOUNT_APPLIED_BEFORE_TAX_Select138 Select138 = "discountAppliedBeforeTax"
	AMOUNT_EXCLUDING_TAX_Select138 Select138 = "amountExcludingTax"
	TAX_CODE_Select138 Select138 = "taxCode"
	TAX_PERCENT_Select138 Select138 = "taxPercent"
	TOTAL_TAX_AMOUNT_Select138 Select138 = "totalTaxAmount"
	AMOUNT_INCLUDING_TAX_Select138 Select138 = "amountIncludingTax"
	INVOICE_DISCOUNT_ALLOCATION_Select138 Select138 = "invoiceDiscountAllocation"
	NET_AMOUNT_Select138 Select138 = "netAmount"
	NET_TAX_AMOUNT_Select138 Select138 = "netTaxAmount"
	NET_AMOUNT_INCLUDING_TAX_Select138 Select138 = "netAmountIncludingTax"
	EXPECTED_RECEIPT_DATE_Select138 Select138 = "expectedReceiptDate"
)
