/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand10 string

// List of $expand10
const (
	PICTURE_Expand10 Expand10 = "picture"
	DEFAULT_DIMENSIONS_Expand10 Expand10 = "defaultDimensions"
	CURRENCY_Expand10 Expand10 = "currency"
	PAYMENT_TERM_Expand10 Expand10 = "paymentTerm"
	PAYMENT_METHOD_Expand10 Expand10 = "paymentMethod"
)
