/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand16 string

// List of $expand16
const (
	ITEM_Expand16 Expand16 = "item"
	ACCOUNT_Expand16 Expand16 = "account"
)
