/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select94 string

// List of $select94
const (
	ID_Select94 Select94 = "id"
	CODE_Select94 Select94 = "code"
	DISPLAY_NAME_Select94 Select94 = "displayName"
	ADDRESS_FORMAT_Select94 Select94 = "addressFormat"
	LAST_MODIFIED_DATE_TIME_Select94 Select94 = "lastModifiedDateTime"
)
