/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select112 string

// List of $select112
const (
	NUMBER_Select112 Select112 = "number"
	ACCOUNT_ID_Select112 Select112 = "accountId"
	ACCOUNT_TYPE_Select112 Select112 = "accountType"
	DISPLAY_Select112 Select112 = "display"
	TOTAL_DEBIT_Select112 Select112 = "totalDebit"
	TOTAL_CREDIT_Select112 Select112 = "totalCredit"
	BALANCE_AT_DATE_DEBIT_Select112 Select112 = "balanceAtDateDebit"
	BALANCE_AT_DATE_CREDIT_Select112 Select112 = "balanceAtDateCredit"
	DATE_FILTER_Select112 Select112 = "dateFilter"
)
