/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand2 string

// List of $expand2
const (
	ACCOUNT_Expand2 Expand2 = "account"
	DIMENSION_Expand2 Expand2 = "dimension"
	DIMENSION_VALUE_Expand2 Expand2 = "dimensionValue"
)
