/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand26 string

// List of $expand26
const (
	JOURNAL_LINES_Expand26 Expand26 = "journalLines"
	ACCOUNT_Expand26 Expand26 = "account"
)
