/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand68 string

// List of $expand68
const (
	PURCHASE_INVOICE_LINES_Expand68 Expand68 = "purchaseInvoiceLines"
	PDF_DOCUMENT_Expand68 Expand68 = "pdfDocument"
	VENDOR_Expand68 Expand68 = "vendor"
	CURRENCY_Expand68 Expand68 = "currency"
)
