/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand6 string

// List of $expand6
const (
	CUSTOMER_FINANCIAL_DETAILS_Expand6 Expand6 = "customerFinancialDetails"
	PICTURE_Expand6 Expand6 = "picture"
	DEFAULT_DIMENSIONS_Expand6 Expand6 = "defaultDimensions"
	CURRENCY_Expand6 Expand6 = "currency"
	PAYMENT_TERM_Expand6 Expand6 = "paymentTerm"
	SHIPMENT_METHOD_Expand6 Expand6 = "shipmentMethod"
	PAYMENT_METHOD_Expand6 Expand6 = "paymentMethod"
)
