/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand28 string

// List of $expand28
const (
	ATTACHMENTS_Expand28 Expand28 = "attachments"
	ACCOUNT_Expand28 Expand28 = "account"
)
