/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select134 string

// List of $select134
const (
	GENERAL_LEDGER_ENTRY_NUMBER_Select134 Select134 = "generalLedgerEntryNumber"
	ID_Select134 Select134 = "id"
	FILE_NAME_Select134 Select134 = "fileName"
	BYTE_SIZE_Select134 Select134 = "byteSize"
	CONTENT_Select134 Select134 = "content"
	CREATED_DATE_TIME_Select134 Select134 = "createdDateTime"
)
