/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select150 string

// List of $select150
const (
	VENDOR_ID_Select150 Select150 = "vendorId"
	VENDOR_NUMBER_Select150 Select150 = "vendorNumber"
	NAME_Select150 Select150 = "name"
	TOTAL_PURCHASE_AMOUNT_Select150 Select150 = "totalPurchaseAmount"
	DATE_FILTER_FILTER_ONLY_Select150 Select150 = "dateFilter_FilterOnly"
)
