/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select42 string

// List of $select42
const (
	ID_Select42 Select42 = "id"
	JOURNAL_DISPLAY_NAME_Select42 Select42 = "journalDisplayName"
	LINE_NUMBER_Select42 Select42 = "lineNumber"
	CUSTOMER_ID_Select42 Select42 = "customerId"
	CUSTOMER_NUMBER_Select42 Select42 = "customerNumber"
	CONTACT_ID_Select42 Select42 = "contactId"
	POSTING_DATE_Select42 Select42 = "postingDate"
	DOCUMENT_NUMBER_Select42 Select42 = "documentNumber"
	EXTERNAL_DOCUMENT_NUMBER_Select42 Select42 = "externalDocumentNumber"
	AMOUNT_Select42 Select42 = "amount"
	APPLIES_TO_INVOICE_ID_Select42 Select42 = "appliesToInvoiceId"
	APPLIES_TO_INVOICE_NUMBER_Select42 Select42 = "appliesToInvoiceNumber"
	DESCRIPTION_Select42 Select42 = "description"
	COMMENT_Select42 Select42 = "comment"
	DIMENSIONS_Select42 Select42 = "dimensions"
	LAST_MODIFIED_DATE_TIME_Select42 Select42 = "lastModifiedDateTime"
)
