/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand20 string

// List of $expand20
const (
	CUSTOMER_PAYMENTS_Expand20 Expand20 = "customerPayments"
	ACCOUNT_Expand20 Expand20 = "account"
)
