/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand string

// List of $expand
const (
	PICTURE_Expand Expand = "picture"
	DEFAULT_DIMENSIONS_Expand Expand = "defaultDimensions"
	ITEM_CATEGORY_Expand Expand = "itemCategory"
)
