/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select54 string

// List of $select54
const (
	PARENT_ID_Select54 Select54 = "parentId"
	ID_Select54 Select54 = "id"
	FILE_NAME_Select54 Select54 = "fileName"
	BYTE_SIZE_Select54 Select54 = "byteSize"
	CONTENT_Select54 Select54 = "content"
	LAST_MODIFIED_DATE_TIME_Select54 Select54 = "lastModifiedDateTime"
)
