/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select148 string

// List of $select148
const (
	CUSTOMER_ID_Select148 Select148 = "customerId"
	CUSTOMER_NUMBER_Select148 Select148 = "customerNumber"
	NAME_Select148 Select148 = "name"
	TOTAL_SALES_AMOUNT_Select148 Select148 = "totalSalesAmount"
	DATE_FILTER_FILTER_ONLY_Select148 Select148 = "dateFilter_FilterOnly"
)
