/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand66 string

// List of $expand66
const (
	GENERAL_LEDGER_ENTRY_Expand66 Expand66 = "generalLedgerEntry"
)
