/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select6 string

// List of $select6
const (
	PARENT_ID_Select6 Select6 = "parentId"
	DIMENSION_ID_Select6 Select6 = "dimensionId"
	DIMENSION_CODE_Select6 Select6 = "dimensionCode"
	DIMENSION_VALUE_ID_Select6 Select6 = "dimensionValueId"
	DIMENSION_VALUE_CODE_Select6 Select6 = "dimensionValueCode"
	POSTING_VALIDATION_Select6 Select6 = "postingValidation"
)
