/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Expand54 string

// List of $expand54
const (
	SALES_QUOTE_LINES_Expand54 Expand54 = "salesQuoteLines"
	PDF_DOCUMENT_Expand54 Expand54 = "pdfDocument"
	CUSTOMER_Expand54 Expand54 = "customer"
	CURRENCY_Expand54 Expand54 = "currency"
	PAYMENT_TERM_Expand54 Expand54 = "paymentTerm"
	SHIPMENT_METHOD_Expand54 Expand54 = "shipmentMethod"
)
