/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select108 string

// List of $select108
const (
	VENDOR_ID_Select108 Select108 = "vendorId"
	VENDOR_NUMBER_Select108 Select108 = "vendorNumber"
	NAME_Select108 Select108 = "name"
	CURRENCY_CODE_Select108 Select108 = "currencyCode"
	BALANCE_DUE_Select108 Select108 = "balanceDue"
	CURRENT_AMOUNT_Select108 Select108 = "currentAmount"
	PERIOD1_AMOUNT_Select108 Select108 = "period1Amount"
	PERIOD2_AMOUNT_Select108 Select108 = "period2Amount"
	PERIOD3_AMOUNT_Select108 Select108 = "period3Amount"
	AGED_AS_OF_DATE_Select108 Select108 = "agedAsOfDate"
	PERIOD_LENGTH_FILTER_Select108 Select108 = "periodLengthFilter"
)
