/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select22 string

// List of $select22
const (
	ID_Select22 Select22 = "id"
	NUMBER_Select22 Select22 = "number"
	DISPLAY_NAME_Select22 Select22 = "displayName"
	ADDRESS_Select22 Select22 = "address"
	PHONE_NUMBER_Select22 Select22 = "phoneNumber"
	EMAIL_Select22 Select22 = "email"
	WEBSITE_Select22 Select22 = "website"
	TAX_REGISTRATION_NUMBER_Select22 Select22 = "taxRegistrationNumber"
	CURRENCY_ID_Select22 Select22 = "currencyId"
	CURRENCY_CODE_Select22 Select22 = "currencyCode"
	IRS1099_CODE_Select22 Select22 = "irs1099Code"
	PAYMENT_TERMS_ID_Select22 Select22 = "paymentTermsId"
	PAYMENT_METHOD_ID_Select22 Select22 = "paymentMethodId"
	TAX_LIABLE_Select22 Select22 = "taxLiable"
	BLOCKED_Select22 Select22 = "blocked"
	BALANCE_Select22 Select22 = "balance"
	LAST_MODIFIED_DATE_TIME_Select22 Select22 = "lastModifiedDateTime"
)
