/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select126 string

// List of $select126
const (
	ID_Select126 Select126 = "id"
	NUMBER_Select126 Select126 = "number"
	EXTERNAL_DOCUMENT_NUMBER_Select126 Select126 = "externalDocumentNumber"
	CREDIT_MEMO_DATE_Select126 Select126 = "creditMemoDate"
	DUE_DATE_Select126 Select126 = "dueDate"
	CUSTOMER_ID_Select126 Select126 = "customerId"
	CONTACT_ID_Select126 Select126 = "contactId"
	CUSTOMER_NUMBER_Select126 Select126 = "customerNumber"
	CUSTOMER_NAME_Select126 Select126 = "customerName"
	BILL_TO_NAME_Select126 Select126 = "billToName"
	BILL_TO_CUSTOMER_ID_Select126 Select126 = "billToCustomerId"
	BILL_TO_CUSTOMER_NUMBER_Select126 Select126 = "billToCustomerNumber"
	SELLING_POSTAL_ADDRESS_Select126 Select126 = "sellingPostalAddress"
	BILLING_POSTAL_ADDRESS_Select126 Select126 = "billingPostalAddress"
	CURRENCY_ID_Select126 Select126 = "currencyId"
	CURRENCY_CODE_Select126 Select126 = "currencyCode"
	PAYMENT_TERMS_ID_Select126 Select126 = "paymentTermsId"
	SHIPMENT_METHOD_ID_Select126 Select126 = "shipmentMethodId"
	SALESPERSON_Select126 Select126 = "salesperson"
	PRICES_INCLUDE_TAX_Select126 Select126 = "pricesIncludeTax"
	DISCOUNT_AMOUNT_Select126 Select126 = "discountAmount"
	DISCOUNT_APPLIED_BEFORE_TAX_Select126 Select126 = "discountAppliedBeforeTax"
	TOTAL_AMOUNT_EXCLUDING_TAX_Select126 Select126 = "totalAmountExcludingTax"
	TOTAL_TAX_AMOUNT_Select126 Select126 = "totalTaxAmount"
	TOTAL_AMOUNT_INCLUDING_TAX_Select126 Select126 = "totalAmountIncludingTax"
	STATUS_Select126 Select126 = "status"
	LAST_MODIFIED_DATE_TIME_Select126 Select126 = "lastModifiedDateTime"
	INVOICE_ID_Select126 Select126 = "invoiceId"
	INVOICE_NUMBER_Select126 Select126 = "invoiceNumber"
	PHONE_NUMBER_Select126 Select126 = "phoneNumber"
	EMAIL_Select126 Select126 = "email"
)
