/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select2 string

// List of $select2
const (
	ID_Select2 Select2 = "id"
	NUMBER_Select2 Select2 = "number"
	DISPLAY_NAME_Select2 Select2 = "displayName"
	TYPE__Select2 Select2 = "type"
	ITEM_CATEGORY_ID_Select2 Select2 = "itemCategoryId"
	ITEM_CATEGORY_CODE_Select2 Select2 = "itemCategoryCode"
	BLOCKED_Select2 Select2 = "blocked"
	BASE_UNIT_OF_MEASURE_ID_Select2 Select2 = "baseUnitOfMeasureId"
	BASE_UNIT_OF_MEASURE_Select2 Select2 = "baseUnitOfMeasure"
	GTIN_Select2 Select2 = "gtin"
	INVENTORY_Select2 Select2 = "inventory"
	UNIT_PRICE_Select2 Select2 = "unitPrice"
	PRICE_INCLUDES_TAX_Select2 Select2 = "priceIncludesTax"
	UNIT_COST_Select2 Select2 = "unitCost"
	TAX_GROUP_ID_Select2 Select2 = "taxGroupId"
	TAX_GROUP_CODE_Select2 Select2 = "taxGroupCode"
	LAST_MODIFIED_DATE_TIME_Select2 Select2 = "lastModifiedDateTime"
)
