/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select136 string

// List of $select136
const (
	ID_Select136 Select136 = "id"
	NUMBER_Select136 Select136 = "number"
	INVOICE_DATE_Select136 Select136 = "invoiceDate"
	DUE_DATE_Select136 Select136 = "dueDate"
	VENDOR_INVOICE_NUMBER_Select136 Select136 = "vendorInvoiceNumber"
	VENDOR_ID_Select136 Select136 = "vendorId"
	VENDOR_NUMBER_Select136 Select136 = "vendorNumber"
	VENDOR_NAME_Select136 Select136 = "vendorName"
	PAY_TO_NAME_Select136 Select136 = "payToName"
	PAY_TO_CONTACT_Select136 Select136 = "payToContact"
	PAY_TO_VENDOR_ID_Select136 Select136 = "payToVendorId"
	PAY_TO_VENDOR_NUMBER_Select136 Select136 = "payToVendorNumber"
	SHIP_TO_NAME_Select136 Select136 = "shipToName"
	SHIP_TO_CONTACT_Select136 Select136 = "shipToContact"
	BUY_FROM_ADDRESS_Select136 Select136 = "buyFromAddress"
	PAY_TO_ADDRESS_Select136 Select136 = "payToAddress"
	SHIP_TO_ADDRESS_Select136 Select136 = "shipToAddress"
	CURRENCY_ID_Select136 Select136 = "currencyId"
	CURRENCY_CODE_Select136 Select136 = "currencyCode"
	PRICES_INCLUDE_TAX_Select136 Select136 = "pricesIncludeTax"
	DISCOUNT_AMOUNT_Select136 Select136 = "discountAmount"
	DISCOUNT_APPLIED_BEFORE_TAX_Select136 Select136 = "discountAppliedBeforeTax"
	TOTAL_AMOUNT_EXCLUDING_TAX_Select136 Select136 = "totalAmountExcludingTax"
	TOTAL_TAX_AMOUNT_Select136 Select136 = "totalTaxAmount"
	TOTAL_AMOUNT_INCLUDING_TAX_Select136 Select136 = "totalAmountIncludingTax"
	STATUS_Select136 Select136 = "status"
	LAST_MODIFIED_DATE_TIME_Select136 Select136 = "lastModifiedDateTime"
)
