/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select76 string

// List of $select76
const (
	ID_Select76 Select76 = "id"
	CODE_Select76 Select76 = "code"
	DISPLAY_NAME_Select76 Select76 = "displayName"
	LAST_MODIFIED_DATE_TIME_Select76 Select76 = "lastModifiedDateTime"
)
