/*
 * Dynamics 365 Business Central
 *
 * Business Central Standard APIs
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package businesscentralsdk

type Select74 string

// List of $select74
const (
	ID_Select74 Select74 = "id"
	CODE_Select74 Select74 = "code"
	DISPLAY_NAME_Select74 Select74 = "displayName"
	SYMBOL_Select74 Select74 = "symbol"
	AMOUNT_DECIMAL_PLACES_Select74 Select74 = "amountDecimalPlaces"
	AMOUNT_ROUNDING_PRECISION_Select74 Select74 = "amountRoundingPrecision"
	LAST_MODIFIED_DATE_TIME_Select74 Select74 = "lastModifiedDateTime"
)
